In [2]:
x = lambda x: x + 10
print(x(10))

x = lambda x, y: x ** y
print(x(5, 2))

20
25

In [3]:
full_name = lambda first_name, last_name: first_name + ' ' + last_name
print(full_name('Dua', 'Lipa'))

Dua Lipa

In [5]:
age_check = lambda age: True if age >= 18 else False
print(age_check(32))

True

In [8]:
data = [(1, 'starfruit'), (10, 'banana'), (3, 'cherry')]

sorted_list = sorted(data, key=lambda x: x[1])
print(sorted_list)

[(10, 'banana'), (3, 'cherry'), (1, 'starfruit')]

In [11]:
numbers = [x for x in range(1, 11)]

filtered_numbers = list(filter(lambda x: x % 2 == 0, numbers))
filtered_numbers

[2, 4, 6, 8, 10]

In [13]:
squared_numbers = list(map(lambda x: x ** 2, numbers))
print(squared_numbers)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [14]:
def add_five(x):
    return x + 5

summed_5 = list(map(add_five, numbers))
print(summed_5)

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [16]:
summed = list(map(lambda x, y: x + y, numbers, summed_5))
print(summed)

[7, 9, 11, 13, 15, 17, 19, 21, 23, 25]

In [17]:
import pandas as pd

df = pd.DataFrame({'Score': [45, 67, 89, 34, 56]})
df['Grade'] = df['Score'].map(lambda x: 'Pass' if x >= 70 else 'Fail')
print(df)

   Score Grade
0     45  Fail
1     67  Fail
2     89  Pass
3     34  Fail
4     56  Fail

In [25]:
mapping = {'A':'Excellent', 'B':'Good','C':'Average'}
df = pd.DataFrame({'Grade': ['A', 'B', 'C', 'A']})
df['Feedback'] = df['Grade'].map(mapping)
df

  Grade   Feedback
0     A  Excellent
1     B       Good
2     C    Average
3     A  Excellent

In [26]:
import random
df = pd.DataFrame({'Employee': ['John', 'Sara', 'Mike']})
df['Performance'] = df['Employee'].map(lambda name: random.randint(1, 100))
df

  Employee  Performance
0     John           12
1     Sara           96
2     Mike           80

In [30]:
import numpy as np

arr = np.array([1.5, 2.7, 3.9, 4.1])
rounded_arr = np.array(list(map(np.round, arr)))
rounded_arr

array([2., 3., 4., 4.])

In [24]:
from itertools import permutations

perm = permutations([1, 2, 3])

for _ in list(perm):
    print(list(_))

[1, 2, 3]
[1, 3, 2]
[2, 1, 3]
[2, 3, 1]
[3, 1, 2]
[3, 2, 1]